# Generated by Django 5.2.13 on 2026-08-17 16:48

import django.db.models.deletion
import project4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(default=project4.models.generate_participant_code, max_length=32, unique=True)),
                ('condition_order', models.CharField(choices=[('AB', 'AB'), ('BA', 'BA')], max_length=2)),
                ('seed', models.PositiveIntegerField()),
                ('current_step', models.CharField(choices=[('consent', 'consent'), ('background', 'background'), ('instructions', 'instructions'), ('practice', 'practice'), ('condition_1', 'condition_1'), ('questionnaire_1', 'questionnaire_1'), ('break', 'break'), ('condition_2', 'condition_2'), ('questionnaire_2', 'questionnaire_2'), ('heldout', 'heldout'), ('final', 'final'), ('complete', 'complete')], default='consent', max_length=32)),
                ('consented', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('background', 'Background'), ('condition', 'Condition'), ('final', 'Final')], max_length=16)),
                ('condition', models.CharField(blank=True, choices=[('pairwise', 'Pairwise'), ('ranking', 'Ranking')], max_length=16, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='project4.studysession')),
            ],
            options={
                'ordering': ['session_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('practice', 'Practice'), ('main', 'Main'), ('heldout', 'Held-out')], default='main', max_length=16)),
                ('task_index', models.PositiveIntegerField()),
                ('movie_ids', models.JSONField()),
                ('ranked_movie_ids', models.JSONField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_trials', to='project4.studysession')),
            ],
            options={
                'ordering': ['session_id', 'block', 'task_index'],
                'unique_together': {('session', 'block', 'task_index')},
            },
        ),
        migrations.CreateModel(
            name='PairwiseTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('practice', 'Practice'), ('main', 'Main'), ('heldout', 'Held-out')], default='main', max_length=16)),
                ('task_index', models.PositiveIntegerField()),
                ('left_movie_id', models.PositiveIntegerField()),
                ('right_movie_id', models.PositiveIntegerField()),
                ('chosen_movie_id', models.PositiveIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_trials', to='project4.studysession')),
            ],
            options={
                'ordering': ['session_id', 'block', 'task_index'],
                'unique_together': {('session', 'block', 'task_index')},
            },
        ),
    ]
