# Generated by Django 5.2.13 on 2026-08-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceModelFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('pairwise', 'Pairwise'), ('ranking', 'Ranking')], max_length=16)),
                ('weights', models.JSONField()),
                ('n_observations', models.PositiveIntegerField(default=0)),
                ('heldout_accuracy', models.FloatField(blank=True, null=True)),
                ('heldout_log_loss', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to='project4.studysession')),
            ],
            options={
                'ordering': ['session_id', 'condition'],
                'unique_together': {('session', 'condition')},
            },
        ),
    ]
