# Generated by Django 5.2.13 on 2026-04-26 17:59

import django.db.models.deletion
import project1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('algorithm', models.CharField(choices=[('logreg', 'Logistic Regression'), ('rf_clf', 'Random Forest'), ('svm', 'Support Vector Machine'), ('knn_clf', 'K-Nearest Neighbors'), ('dt_clf', 'Decision Tree'), ('linreg', 'Linear Regression'), ('rf_reg', 'Random Forest'), ('svr', 'Support Vector Regressor'), ('knn_reg', 'K-Nearest Neighbors'), ('dt_reg', 'Decision Tree')], max_length=20)),
                ('metric', models.CharField(choices=[('accuracy', 'Accuracy'), ('f1', 'F1 (weighted)'), ('precision', 'Precision (weighted)'), ('recall', 'Recall (weighted)'), ('r2', 'R²'), ('rmse', 'RMSE'), ('mae', 'MAE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to=project1.models.trained_model_upload_path)),
                ('train_score', models.FloatField(blank=True, null=True)),
                ('test_score', models.FloatField(blank=True, null=True)),
                ('train_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('train_error', models.TextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='project1.experiment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
