# Generated by Django 5.2.13 on 2026-05-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0007_experiment_excluded_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='hyperparameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
