# Generated by Django 5.2.13 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_trainedmodel_hyperparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='cv_folds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='cv_scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
